### ISSUE TITLE
What gateway/bridge is required?

### ISSUE THREAD

**Issue by jwelter1971** [dieselrabbit/screenlogicpy#10]
Sorry but could not find this information.

What gateway is needed?  Does a simple RS485 to IP bridge work or do you need the Pentair Screenlogic protocol adapter?  P/N 520500

**Comment by dieselrabbit** [comment]
This implementation has been authored to support the Pentair ScreenLogic protocol adapter, P/N 520500. It was not intended to, nor do I think it will, work with a more direct RS485 to IP bridge type connection. 

From looking at other projects that support that connection type (https://github.com/tagyoureit/nodejs-poolController), it seems the protocol is different, both in the query codes and the format of the responses.
