### ISSUE TITLE
async_discover() returns no gateways on Windows

### ISSUE THREAD

**Issue by dieselrabbit** [dieselrabbit/screenlogicpy#12]
Testing on Windows, `async_discover()` returns zero gateways while the refactored `discover()` still functions correctly.

Tested on Windows 10 in Python 3.8.8 64-bit.

Seems to work on Github testing.

**Comment by dieselrabbit** [comment]
Any ideas @bdraco?

**Comment by bdraco** [comment]
If you increase the `asyncio.sleep` time to 2s does it fix it ?

**Comment by dieselrabbit** [comment]
No. Tried 2 initially, and then 10. No result.

**Comment by bdraco** [comment]
Maybe wireshark can show the difference.  I don't actually have a windows machine to test with.

**Comment by dieselrabbit** [comment]
Leaving this here for reference, maybe not related: https://bugs.python.org/issue31922

I'll check Wireshark.

**Comment by bdraco** [comment]
Since we are pre-creating and passing in the socket, there isn't much happening in `create_datagram_endpoint` that could go wrong:

https://github.com/python/cpython/blob/3.8/Lib/asyncio/base_events.py#L1215

I'm at a loss as to why it doesn't work on windows only.

**Comment by dieselrabbit** [comment]
Same. Wireshark comms match the working non-asyncio version. Both the broadcast and response are witnessed.

**Comment by bdraco** [comment]
Does `datagram_received` `connection_made` and/or `connection_lost` ever get called on the windows machine in question?

**Comment by dieselrabbit** [comment]
`connection_made` hits, then `error_received` with:

```
Exception in callback _ProactorDatagramTransport._loop_reading()
handle: <Handle _ProactorDatagramTransport._loop_reading()>
Traceback (most recent call last):
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 566, in _loop_reading
    self._read_fut = self._loop._proactor.recvfrom(self._sock,
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 494, in recvfrom
    ov.WSARecvFrom(conn.fileno(), nbytes, flags)
OSError: [WinError 10022] An invalid argument was supplied
```
`datagram_received` never hits. `connection_lost` only after the transport is closed.

**Comment by bdraco** [comment]
If we don't pre-create the socket, does it work?

```
diff --git a/screenlogicpy/discovery.py b/screenlogicpy/discovery.py
index 8b755ee..4869ceb 100644
--- a/screenlogicpy/discovery.py
+++ b/screenlogicpy/discovery.py
@@ -130,10 +130,10 @@ def discover():
 async def async_discover():
     """Discover screenlogic gateways."""
     loop = asyncio.get_event_loop()
-    udp_sock = create_broadcast_socket()
     transport, protocol = await loop.create_datagram_endpoint(
         lambda: ScreenLogicDiscoveryProtocol(),  # pylint: disable=unnecessary-lambda
-        sock=udp_sock,
+        family=socket.AF_INET,
+        allow_broadcast=True,
     )
     try:
         transport.sendto(DISCOVERY_PAYLOAD, (DISCOVERY_ADDRESS, DISCOVERY_PORT))
```

**Comment by dieselrabbit** [comment]
Wireshark sees a broadcast and a response, but `datagram_received` is still never called.

**Comment by bdraco** [comment]
This is a bit of a shot in the dark, but maybe windows wants an explicit bind call

```
diff --git a/screenlogicpy/discovery.py b/screenlogicpy/discovery.py
index 8b755ee..1bd05cf 100644
--- a/screenlogicpy/discovery.py
+++ b/screenlogicpy/discovery.py
@@ -27,9 +27,9 @@ _LOGGER = logging.getLogger(__name__)
 
 def create_broadcast_socket():
     """Create a broadcast soscket for discovery."""
-    addressfamily = socket.AF_INET
-    udp_sock = socket.socket(addressfamily, socket.SOCK_DGRAM)
+    udp_sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
     udp_sock.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
+    udp_sock.bind(("", 0))
     return udp_sock
 
 
```

**Comment by dieselrabbit** [comment]
Bingo. I just found this too, but was experimenting with (address, port) combos.

**Comment by dieselrabbit** [comment]
Thank you for all your assistance!

**Comment by dieselrabbit** [comment]
Fixed with https://github.com/dieselrabbit/screenlogicpy/commit/2da232e7402a30722862f6678f16a3ccd73e279f
