### ISSUE TITLE
Discovery only returns the first gateway.

### ISSUE THREAD

**Issue by bdraco** [dieselrabbit/screenlogicpy#2]
Nice work on this!

I've noticed discovery only returns the first gateway.  Adding the integration multiple times was enough to get it to work and find them all if you get lucky enough for the one you want to respond.

<img width="331" alt="Screen_Shot_2021-02-07_at_10_55_38_AM" src="https://user-images.githubusercontent.com/663432/107159297-14507d80-6933-11eb-9481-a8aaa60b4331.png">

roombapy might provide some inspiration:
https://github.com/pschmitt/roombapy/blob/master/roombapy/discovery.py

If you plan on merging this to `core`, feel free to ping me to request a code review.

**Comment by dieselrabbit** [comment]
Thanks! ..and thanks for the feedback. I don't have multiple gateways (and to be honest, didn't imagine many - if any- to have multiple), so I hadn't planned to support it. However based on the 'inspiration' you provided it seems fairly straight-forward so I'm not opposed.

Merging into `core` is the end goal, but this being my first integration or even pypi package, I feel like I've got a ways to go before it's ready for a pull request. I appreciate the offer for a code review and will likely take you up on that!
