### ISSUE TITLE
Inbound update events from the controller?

### ISSUE THREAD

**Issue by ferventgeek** [dieselrabbit/screenlogicpy#20]
I've looked a several libraries for Pentair integration and am really interested in screenlogicpy. My test was a wrapper to automate aftermarket Intelebright 5G LED boards, and your repo is toggling relays well. Screenlogic is an odd piece of work- don't get me started on quirks like it suspending the discovery service when a client app is connected. Long ago I was a product manager, and I can't even. You're doing great work here.

My question is about random inbound status update messages and their interaction with the dict behind the scenes. When the socket to the controller is open, Wireshark suggests that Screenlogic is piping (some) messages from the RS486 bus out to connected clients whenever they're sent on the bus. That's actually good, because I'd love to respond to events that happen via other apps, controllers, or the service panel. However the screenlogicpy api looks to be command/response based for changes to make it easy to use, Hence the global refresh, get_data access model. That's a Good Thing.

Is there an event hook for inbound messages I'm missing, or is that something you'd be interested in me exploring for possible pull into the repo? My additions might be: 

1. An option to enable server push updates to the data dict. Clients could connect and then use the existing get method without the need to request updates first. (But zero change to the existing api or functionality for existing users.)
2. Method for getting the last update date and/or milliseconds since last message. (Both async and full query tracking)
3. An event handler to register callbacks for Screenlogic messages 
4. An option to fire the callback on all messages received (default would be false, event on un-commanded responses only.) 

Thoughts? The driver is a new integration controller, and I'd love to not short-poll and diff against previous data values.

Thanks again for maintaining a great library for an IoT-unfriendly pool stack.

**Comment by dieselrabbit** [comment]
Check out [`protocol.register_async_message_callback`](https://github.com/dieselrabbit/screenlogicpy/blob/57c833aa2a71dae4882a8c6ae93d543d39aa52c5/screenlogicpy/requests/protocol.py#L71). Since the protocol is fully async, it can and will receive unsolicited messages from the protocol adapter, it just needs to know if it should do anything with them. That method can specify the data dict to pass to the callback so the callback can update it. While tested, it has not been used for anything production-wise on my end yet so it may not be super robust.
That should cover 1. and 3. You can do 4., but you'd have to register each message code you wanted to handle individually. Not a huge deal.
I don't have anything to support 2., but in theory you could get that functionality by handling the `logging` messages.

All that said, in my experience the only message I've ever seen screenlogic send on its own is a weather update message, despite more possible messages being listed in the protocol document.

**Comment by ferventgeek** [comment]
Thanks, I'll take a look at that. Yeah I'd need a message router by type, but you've likely already defined the deserializers for them. 

What got me thinking is I tested your project with the IOS app open and the lighting (circuit statuses) controls in the mobile app immediately reflect changes pushed from screenlogicpy. The mobile app can't be polling that fast, so the adapter is pushing *something* to it. The app also seems to get pump metrics in not quite real time, and I'm testing tonight to see if that's latency in the command->pump result, the pump->RS486 bus report delay, polling in the mobile app or all three. But I need to set up a spanning port to capture Screenlogic traffic first. I have a prototype RS486 logger somewhere. 

I may set that back up so I can correlate both sides of the adapter. Gimme a couple weekends. Thanks for the help!

**Comment by dieselrabbit** [comment]
> What got me thinking is I tested your project with the IOS app open and the lighting (circuit statuses) controls in the mobile app immediately reflect changes pushed from screenlogicpy. The mobile app can't be polling that fast, so the adapter is pushing something to it.

This makes me wonder if "push subscription" of sorts is by client type/id and you only get the "pushes" if you're a different client. All the existing documentation mimics the Android app when creating a connection. screenlogicpy does too.

> The app also seems to get pump metrics in not quite real time, and I'm testing tonight to see if that's latency in the command->pump result, the pump->RS486 bus report delay, polling in the mobile app or all three.

This seems to be a pump->bus, or bus->protocol adapter delay. Could be the protocol adapter is _on_ the bus and effectively the same thing. I've tested refreshing the data as quickly as every 5 seconds - the protocol adapter handles it -  but the raw data received doesn't change as fast. Seems to be ~30secs for pump data to update on the protocol adapter.

**Comment by ferventgeek** [comment]
Delay in the panel/pump seems likely. When it's in service mode and the bus routes to the pump directly, there's little latency between command and result, even via the screenlogic. Switching from Auto to Service takes about 20 seconds before the pump's onboard UI comes back up. Could be the panel isolates all the devices "zombifying" them, and then periodically pushes commands to change RPM/flow or report the pumps streaming updates? Anyway, I'll dig in a bit more. Thanks so much.

**Comment by ferventgeek** [comment]
Thanks for your help Kevin. I'm new to asyncio and am going to let it be for now. Got off into loop not running debugging and.. the priority for async changed. Funny that. So I'll be back to this later and will pull screenlogicpy into my project as is. Thanks again.
