### ISSUE TITLE
Feature Request - Freeze Mode on/off

### ISSUE THREAD

**Issue by farberm** [dieselrabbit/screenlogicpy#23]
Any chase we can monitor the freeze mode state?

**Comment by dieselrabbit** [comment]
Freeze mode is considered a circuit configuration and not something often changed after initial setup.  
Just so I'm clear, you're interested in monitoring whether freeze mode has been enabled or disabled for a circuit? Could you describe a use case for this?

**Comment by farberm** [comment]
On the main screen is lists Freeze Mode:  "Yes" ( or "N"o if not active). Just looking to track the Stus of Freeze Mode State mainly. The other option is to track which circuits are designated to turn on during freeze mode. Thanks for you help.

**Comment by dieselrabbit** [comment]
Ah, ok. I think both the current Freeze Mode state and which circuits are set to turn on in freeze mode are already available in the JSON output. 

For the freeze mode state, that value is under the `config->freeze_mode->value` key. I assume `1` is "Yes" and `0` is "No".

For the individual circuits, the `flags` key in each circuit will read a `1` if `yes`, and a `0` if `no`.  I'm not sure though if that is a true bitwise field or just the freeze mode state. Assigning the term `flags` was purely based on how other projects have labeled it. I don't have any info on what other flags might get set there.

**Comment by dieselrabbit** [comment]
Closing this for now. Will re-open if it's determined that these aren't the data points we're looking for.
