### ISSUE TITLE
Circuits marked as "don't show" enumerate in HA

### ISSUE THREAD

**Issue by American1337** [dieselrabbit/screenlogicpy#34]
I have a few circuits that are marked as "don't show" in the pentair desktop app yet enumerate in HA. I'm curious whether that is intended or not?

This might be not a bug as I can mark the entities as hidden myself using home assistant UI. But out of the box it is some clutter, up to you on whether this is a feature or bug. Interestingly Aux 7 doesn't show but the other aux 8/9/10 do show in HA, not sure why some are hidden and others are not.

circuits in HA:

![image](https://user-images.githubusercontent.com/123335700/218322516-496b8ebf-f35e-4f3a-b1e7-ab6be4247850.png)

My circuit config:

![image](https://user-images.githubusercontent.com/123335700/218322253-eb53dcef-7c29-4865-b232-8a448e4d5809.png)
![image](https://user-images.githubusercontent.com/123335700/218322255-60e3b516-9aa8-471e-bb66-03f8ad265f17.png)
![image](https://user-images.githubusercontent.com/123335700/218322260-9deaf2ec-9445-4c55-8430-bd125dc027c6.png)

**Comment by dieselrabbit** [comment]
This is good info and a good bug.
Naively, the HA integration adds-but-disables any circuit with a what is thought to be a generic default name. Based on the information I had at the time, this was `Feature [1-8]`, `Aux [1-7]`, and `AuxEx`. It was a best guess at removing some clutter from the initial setup.
With your info, I've expanded this to `Aux [1-23]`, but it also shouldn't be a problem to respect the "Don't Show" setting from the pool controller. There's work to be done here in the api, but also in the HA integration.

One question: The previous data I have from you lists a different "Show on:" setting for `U Pool Ligh` and `Fiber Optic` that I haven't seen before. Are those set to something other than Pool, Spa, Lights, Features, or Don't Show?

**Comment by American1337** [comment]
All the circuit names had to be reentered after the pentair system power loss/battery backup failed , so some have different names now. 

"U Pool Ligh" is now "Upr Lite" (upper pool light).

But I think I had the same fiber optic name before and after.

**Comment by dieselrabbit** [comment]
For "Upr Lite" and "Fiber Optic", what is the "Show on:" set to?

**Comment by American1337** [comment]
![image](https://user-images.githubusercontent.com/123335700/218333960-2f995876-978a-46e2-b1e3-0c34c429c232.png)
![image](https://user-images.githubusercontent.com/123335700/218333969-2dc3a264-f2cf-42b0-a660-3fb03ff3464f.png)

**Comment by dieselrabbit** [comment]
Interesting. Not what I expected.
Thanks.

**Comment by dieselrabbit** [comment]
Could you provide an updated diagnostic data?

**Comment by American1337** [comment]
[diagnostics.txt](https://github.com/dieselrabbit/screenlogicpy/files/10723452/diagnostics.txt)

**Comment by dieselrabbit** [comment]
I've identified the interface value for "Don't Show" and definition of that has been added to the code. screenlogicpy will need a new release and changes will need to be made in Home Assistant.

**Comment by dieselrabbit** [comment]
Fix will likely be available in 2023.3.0 of Home Assistant.
