### ISSUE TITLE
Super Chlorinate

### ISSUE THREAD

**Issue by dieselrabbit** [dieselrabbit/screenlogicpy#37]
Support enabling and setting timer for super chlorination.

- CLI
- Home Assistant
  - switch: start/stop
  - number: timer value

**Comment by dieselrabbit** [comment]
Can set the values, but as I don't have a SCG, I still need help in identifying the current state.

Outstanding questions:
- Does the scg_status bitmask store state data for the chlorinator other than just 0x01? Is there something more that I need to account for (or can use) beyond 1=on and 0=off?
- Can I confirm that scg_super_chlor_timer can be > 0 and still super chlorination not be active? My tests seem to indicate "yes", but I don't actually have a SCG so it could be invalid.
- Is scg_super_chlor_timer having a value > 0 the only indication that super chlorination is active, or is there additional data in the scg_status bitmask?
- Is the "Start" button in the Chlorinator tab in the ScreenLogic app required to initiate super chlorination for the specified hours, or just a shortcut to setting the hours to 24?
- Is scg_super_chlor_timer a persistent value, or does it count down showing the time remaining? I would need to account for that in the HA implementation.

**Comment by calisro** [comment]
> * Does the scg_status bitmask store state data for the chlorinator other than just 0x01? Is there something more that I need to account for (or can use) beyond 1=on and 0=off?

I don't see any other data in there except for the on/off status (129). 

> * Can I confirm that scg_super_chlor_timer can be > 0 and still super chlorination not be active? My tests seem to indicate "yes", but I don't actually have a SCG so it could be invalid.

It seems to me that the number can't be above zero and SC not active.  You can't even turn off the pump to deactivate it.


> * Is scg_super_chlor_timer having a value > 0 the only indication that super chlorination is active, or is there additional data in the scg_status bitmask?

The only indication that I can see in the diag data is the timer being > 0.



> * Is the "Start" button in the Chlorinator tab in the ScreenLogic app required to initiate super chlorination for the specified hours, or just a shortcut to setting the hours to 24?

Yes you must hit the start button.  Changing the time without hitting start does not adjust anything that I can see.  Hitting start is the only thing that actually sends data.



> * Is scg_super_chlor_timer a persistent value, or does it count down showing the time remaining? I would need to account for that in the HA implementation.

It is persistent.  I set super chlorinate for 3 hours and it was '3' till that time expired and then was zero again.

**Comment by dieselrabbit** [comment]
@calisro This functionality is now present in the the API/CLI with v0.10.0.  That said, I don't have an SCG so I am unable to test IRL. If you are able to give it a try, it would be much appreciated.

**Comment by calisro** [comment]
I downloaded 10.0 and installed it as a custom_component in HA, but I do not see any new entities to control super chlorination.  Maybe i'm just missing something.  Let me know how to test it and I can do it.  Thanks!! 

But I probably just didn't do it right.  I took the zip from here and unzipped it in custom_components/screenlogic but that doesn't look right.

**Comment by dieselrabbit** [comment]
Sorry, there is no support for this in Home Assistant yet, only in the `screenlogicpy` library.

It's possible to test it using the `screenlogicpy` [command line interface](https://github.com/dieselrabbit/screenlogicpy#set-super-chlorinate-sc) if that's something you are comfortable with.
