### ISSUE TITLE
Example Request - Pump RPM

### ISSUE THREAD

**Issue by egusta** [dieselrabbit/screenlogicpy#4]
Can you please provide a working example of a pump decode?

For example, if you would want to see the Pump RPM.

Here's what I tried and I'm not close:

import struct
import screenlogicpy
from screenlogicpy.const import code
from screenlogicpy.requests.utility import sendRecieveMessage, getSome
from test_decode import decode, decodePump #<--A Few changes here

host = screenlogicpy.discovery.discover()
#host = {'ip': 'xxx.xxx.xxx.xxx', 'port':'80'}
try:
    gateway_socket, gateway_mac = screenlogicpy.requests.login.connect_to_gateway(host['ip'], host['port'])
    _version = screenlogicpy.requests.gateway.request_gateway_version(gateway_socket)
    response = sendRecieveMessage(gateway_socket, code.PUMPSTATUS_QUERY, struct.pack("<I", 0))
    #print(response)
    
except screenlogicpy.ScreenLogicError as error:
    print(error)
finally:
    gateway_socket.close()

#toINT(response)
decodePump(response)
#print(testData)
#decode(response)

**Comment by dieselrabbit** [comment]
Your PUMPSTATUS_QUERY struct is not formatted correctly for the query:
`struct.pack("<II", 0, pumpID)`
Check out screenlogicpy/requests/pump.py for both request and decoding examples.

**Comment by dieselrabbit** [comment]
Closing this as the README has been updated with usage examples.
