### ISSUE TITLE
discover() not working

### ISSUE THREAD

**Issue by nash-an** [dieselrabbit/screenlogicpy#6]
Hi, sorry to bother. Just wanna preface by saying this is an amazing library. Super well documented and works amazingly well.
I'm working on a little project that I do want to be able to make open source, but I am running into an issue. 

`screenlogicpy.discovery.discover()` returns nothing. Using the CLI provided in this module gives me `No gateways found`
Using `gateway = ScreenLogicGateway("192.168.X.X")` or `--ip` works as intended.

Probably a simple mistake on my part, but not sure what to look at.

If it means anything my router gateway is `192.168.0.1` as opposed to `192.168.1.1` and ScreenLogic port is 80.

**Comment by dieselrabbit** [comment]
Can you confirm the machine you are running `screenlogicpy` from is on the same subnet as your ScreenLogic gateway? Depending on router configuration, discovery usually doesn't work across different subnets. This can be the case if running from a devcontainer or WSL instance.

**Comment by nash-an** [comment]
They are both on the same subnet. I am not running any containers nor a WSL instance. I am running the python file through the windows powershell, if there is a catch I am not familiar that may be the case. Sorry for the extremely late reply.

**Comment by dieselrabbit** [comment]
Unfortunately, I can't reproduce the issue.

**Comment by nash-an** [comment]
Thank you for trying. I'll see what I can do.
