### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [dieselrabbit/screenlogicpy#8]
Please tag the source. This allows distributions to get the complete source from GitHub and run the tests.

Thanks.

**Comment by dieselrabbit** [comment]
Sorry. Still a bit of a git noob. Could you clarify what you are wanting, and/or point me in the right direction? Is that the same as releases?

**Comment by fabaff** [comment]
Yes, it's the same as "releases". Some like this would add a tag for 0.9.2: `git tag -a 0.9.2 && git push origin 0.9.2`

Or you could do it in the [release section](https://github.com/dieselrabbit/screenlogicpy/releases). Then GitHub will add the tag for you.

**Comment by dieselrabbit** [comment]
Thanks. Just to be clear, do you have a need for me to tag prior releases, or just ones going forward?

**Comment by fabaff** [comment]
No, prior releases needed. For NixOS we have [started](https://github.com/NixOS/nixpkgs/pull/118767) with 0.3.0.

**Comment by dieselrabbit** [comment]
Done. https://github.com/dieselrabbit/screenlogicpy/releases/tag/v0.3.0

**Comment by fabaff** [comment]
Thank you.
